name: RSpec

on:
  pull_request:
    branches:
      - main

jobs:
  rspec:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3 # change if needed
          bundler-cache: true

      - name: Run RSpec
        run: |
          bundle install
          bundle exec rspec
